# Generated by Django 2.2.15 on 2020-09-15 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=255, verbose_name='Name')),
                ('region', models.CharField(blank=True, max_length=63, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=63, verbose_name='City / Town')),
                ('country', models.CharField(blank=True, max_length=127, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('all_day', models.BooleanField(default=False, verbose_name='all day')),
                ('repeat', models.CharField(choices=[('NEVER', 'Never'), ('DAILY', 'Every Day'), ('WEEKDAY', 'Every Weekday'), ('WEEKLY', 'Every Week'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Every Month'), ('YEARLY', 'Every Year')], default='NEVER', max_length=15, verbose_name='repeat')),
                ('end_repeat', models.DateField(blank=True, null=True, verbose_name='end repeat')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/', verbose_name='thumbnail')),
                ('categories', models.ManyToManyField(blank=True, to='events.Category', verbose_name='categories')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('location', models.ManyToManyField(blank=True, to='events.Location', verbose_name='locations')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
